import { useEffect, useState } from 'react';
import { api, setAuthToken, setUnauthorizedHandler } from './api/client';
import type { ApiCase, User } from './types';
import { LandingAuth } from './components/LandingAuth'; import { Navbar } from './components/Navbar'; import { CaseDashboard } from './components/CaseDashboard'; import { ChatScreen } from './components/ChatScreen'; import { AuditLogScreen } from './components/AuditLogScreen'; import { PrepareWorkspace } from './components/PrepareWorkspace'; import { DocumentList } from './components/DocumentList';
type Screen = 'dashboard' | 'chat' | 'audit' | 'prepare' | 'documents' | 'doc-chat';
export default function App() {
  const [user, setUser] = useState<User | null>(null); const [cases, setCases] = useState<ApiCase[]>([]); const [caseItem, setCaseItem] = useState<ApiCase | null>(null); const [screen, setScreen] = useState<Screen>('dashboard'); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [docId, setDocId] = useState<string | null>(null); const [docFilename, setDocFilename] = useState<string | null>(null);
  const logout = () => { setAuthToken(null); setUser(null); setCases([]); setCaseItem(null); setScreen('dashboard'); setDocId(null); setDocFilename(null); };
  useEffect(() => { setUnauthorizedHandler(logout); return () => setUnauthorizedHandler(null); }, []);
  const refreshCases = async () => { setLoading(true); setError(''); try { const result = await api.getCases(); setCases(result); return result as ApiCase[]; } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load cases'); return []; } finally { setLoading(false); } };
  const login = async (username: string, password: string) => { setError(''); const result = await api.login(username, password); setAuthToken(result.token); setUser(result.user); const loaded = await refreshCases(); setScreen(loaded.length ? 'dashboard' : 'prepare'); };
  if (!user) return <LandingAuth onLogin={login} error={error} />;
  return <div className="min-h-screen bg-slate-50 text-slate-900"><Navbar user={user} screen={screen} currentCase={caseItem} onNavigate={setScreen} onLogout={logout} />{loading && <p className="text-center p-3 text-sm text-slate-500">Loading vault data…</p>}{error && <p className="mx-auto mt-4 max-w-6xl rounded border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}<main>{screen === 'prepare' && <PrepareWorkspace onReady={async item => { const loaded = await refreshCases(); setCases(loaded); setCaseItem(item); setScreen('dashboard'); }} />} {screen === 'dashboard' && <CaseDashboard cases={cases} user={user} onSelect={item => { setCaseItem(item); setScreen('documents'); }} onAudit={() => setScreen('audit')} />} {screen === 'chat' && caseItem && <ChatScreen caseItem={caseItem} user={user} />} {screen === 'audit' && <AuditLogScreen />} {screen === 'documents' && caseItem && <DocumentList caseId={caseItem.case_id} onViewDoc={(id) => { setDocId(id); /* F12 will hook Viewer here */ }} onOpenDocChat={(id, name) => { setDocId(id); setDocFilename(name); setScreen('doc-chat'); }} />} {screen === 'doc-chat' && caseItem && <ChatScreen caseItem={caseItem} user={user} documentId={docId || undefined} documentFilename={docFilename || undefined} />}</main></div>;
}
